# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b0e6b5f8caf7686d4a7976d935b4312c5613b433b999738cbf9976e2f63fdfd3ff1c26201bd2f42cbb7bb2b885793a98e003c352f15348c40dabfe6a22e0540

test:
  secret_key_base: 3b0cb646eb144cb2527384e7443792e56cd455f7a2ebb0bacf110324b68b24e56fbfdc61ef7fe43086700b7ef0837e8a1147d5fe6f627c7824b7cd8558d285ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
